### PR TITLE
fix(wallet_list): add SafeArea to wallet list

### LINKED ISSUE #106: The wallet list doesn't scroll to the bottom
image

### PR DESCRIPTION
**Pull request by gabaldon**
Adds SafeArea to avoid hide content by the bottom-bar of the device.

close #106

### CODE REVIEW

File: lib/widgets/wallet_list.dart [hunk 1]
```diff
@@ -88,6 +88,24 @@ class WalletListState extends State<WalletList> {
...
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
+        walletIdList.add(value.id);
```
Comment (aesedepece) [inline lib/widgets/wallet_list.dart:108]: ???

**Review by aesedepece — CHANGES_REQUESTED** [review]

File: lib/widgets/wallet_list.dart (hunk 1 above)
Comment (Tommytrg) [reply lib/widgets/wallet_list.dart:108]: It' a trick to debug the wallet list :shushing_face:

**Review by Tommytrg — APPROVED** [review]
