### PR TITLE
fix: format number

### LINKED ISSUE #296: Add coma separator for numbers greater than 999
Current number format:  300000.45
Expected number format: 300,000.45

### PR DESCRIPTION
**Pull request by gabaldon**
close #296

### CODE REVIEW

File: lib/util/extensions/num_extensions.dart [hunk 1]
```diff
@@ -1,6 +1,17 @@
...
+
+final formatter = NumberFormat('#,###,000');
+String format(result) {
+  List parts = result.toString().split('.');
+  if (parts.length > 1) {
+    return '${parts[0].toString().length < 3 ? parts[0] : formatter.format(num.tryParse(parts[0]) ?? 0)}.${parts[1]}';
+  } else {
+    return '${parts[0].toString().length < 3 ? parts[0] : formatter.format(num.tryParse(parts[0]) ?? 0)}';
+  }
+}
```
Comment (Tommytrg) [inline lib/util/extensions/num_extensions.dart:14]: I think we could extract some repeated code. 
- We could add `parts[0].toString().length < 3` and `formatter.format(num.tryParse(parts[0]) ?? 0)}.${parts[1]}'` in variables.
- Return first `parts[0]` if the condition matches

**Review by Tommytrg — APPROVED** [review]
