### PR TITLE
fix: show unsufficient funds error when selecting inputs

### LINKED ISSUE #464: Show insufficient funds error when building the inputs for the vtt
`witnet.dart` need to throw insufficient funds error when selecting UTXOS, instead of returning an empty array.
`myWitWallet` needs to show an erroravoiding going forward to select miner fee.

### PR DESCRIPTION
**Pull request by gabaldon**
Block by https://github.com/witnet/witnet.dart/pull/37

close #464

### CODE REVIEW

File: lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart [hunk 1]
```diff
@@ -445,14 +463,22 @@ class VTTCreateBloc extends Bloc<VTTCreateEvent, VTTCreateState> {
...
+          status: VTTCreateStatus.exception, message: 'Insufficient funds'));
+    }
     setEstimatedWeightedFees();
     emit(
       state.copyWith(
-          inputs: inputs, outputs: outputs, status: VTTCreateStatus.building),
+          inputs: inputs,
+          outputs: outputs,
+          status: VTTCreateStatus.building,
+          message: null),
```
Comment (Tommytrg) [inline lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart:481]: Why `null` instead of `''`?

File: lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart [hunk 2]
```diff
@@ -350,70 +352,65 @@ class VTTCreateBloc extends Bloc<VTTCreateEvent, VTTCreateState> {
...
+    feeNanoWit = getFee();
+    valueOwedNanoWit += feeNanoWit;
 
-      if (feeType == FeeType.Weighted) {
-        /// calculate change
-        valueChangeNanoWit = (valuePaidNanoWit - valueOwedNanoWit);
+    /// compare to balance
+    if (balanceNanoWit < valueOwedNanoWit) {
+      /// TODO:: throw insufficient funds exception
+    } else {
```
Comment (Tommytrg) [inline lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart:382]:
```suggestion
    if (balanceNanoWit > valueOwedNanoWit) {
```

Comment (Tommytrg) [inline lib/bloc/transactions/value_transfer/vtt_create/vtt_create_bloc.dart]:
```suggestion
    if (balanceNanoWit > valueOwedNanoWit) {
```

File: lib/screens/send_transaction/send_vtt_screen.dart [hunk 3]
```diff
@@ -221,8 +226,26 @@ class CreateVttScreenState extends State<CreateVttScreen>
   }
 
   BlocListener _vttCreateBlocListener() {
+    final theme = Theme.of(context);
     return BlocListener<VTTCreateBloc, VTTCreateState>(
-      listener: (BuildContext context, VTTCreateState state) {},
+      listener: (BuildContext context, VTTCreateState state) {
+        if (state.vttCreateStatus == VTTCreateStatus.exception &&
```
Comment (Tommytrg) [inline lib/screens/send_transaction/send_vtt_screen.dart:232]: Can we create a method to have this logic in `VTTCreateState`?

```dart
/// VTTCreateState
  bool isExceptionStatus() {
    return vttCreateStatus == VTTCreateStatus.exception &&
        message != null &&
        message!.contains(INSUFFICIENT_FUNDS_ERROR);
  }
```

**Review by Tommytrg — APPROVED** [review]
