### PR TITLE
fix: add mintvtt to db if not saved and new utxo list

### LINKED ISSUE #377: Wallet does not show newly mined blocks
On Telegram, a wallet user noticed that the wallet transaction view does not show newly mined blocks. I checked the explorer for the address he shared and tried the API call which both show newly mined blocks. Thus, it appears there is something wrong with the way the transaction view is generated (for newly mined blocks).

### PR DESCRIPTION
**Pull request by gabaldon**
close #377

### CODE REVIEW

File: lib/util/storage/database/transaction_repository.dart [hunk 1]
```diff
@@ -211,13 +211,27 @@ class MintRepository extends _TransactionRepository {
...
     }
     return true;
   }
+
+  Future<MintEntry?> getTransaction(
+      String txHash, DatabaseClient databaseClient) async {
+    try {
+      dynamic mintInfoDbJson = await _store.record(txHash).get(databaseClient);
+
+      MintEntry valueTransferInfo = MintEntry.fromJson(mintInfoDbJson);
```
Comment (parodyBit) [inline lib/util/storage/database/transaction_repository.dart:230]: rename this variable since it is not a valueTransfer
```suggestion
      MintEntry mintEntry = MintEntry.fromJson(mintInfoDbJson);
```

File: lib/bloc/explorer/explorer_bloc.dart [hunk 2]
```diff
@@ -319,6 +321,87 @@ class ExplorerBloc extends Bloc<ExplorerEvent, ExplorerState> {
...
+      rethrow;
+    }
+  }
+
+  Future<Account> _updateAccountMintsFromExplorer(Account account) async {
+    try {
+      /// retrieve all Block Hashes
+      final addressBlocks = await explorer.address(
+          value: account.address, tab: 'blocks') as AddressBlocks;
+      print(addressBlocks.blocks.length);
```
Comment (parodyBit) [inline lib/bloc/explorer/explorer_bloc.dart:359]: remove debug print
```suggestion
      
```
