### PR TITLE
fix: remove duplicate time labels

### LINKED ISSUE #600: Avoid duplicated time label in transaction list
Delete duplicated time label in transaction list

### PR DESCRIPTION
**Pull request by parodyBit**
Close #600

### CODE REVIEW

File: lib/widgets/transactions_list.dart [hunk 1]
```diff
@@ -63,7 +63,11 @@ class TransactionsListState extends State<TransactionsList> {
         itemBuilder: (context, index) {
           GeneralTransaction transaction = widget.transactions[index];
           return TransactionsItem(
-              transaction: transaction, showDetails: widget.setDetails);
+            transaction: transaction,
+            showDetails: widget.setDetails,
+            previousTxnTime:
+                index > 1 ? widget.transactions[index - 1].txnTime : null,
```
Comment (gabaldon) [inline lib/widgets/transactions_list.dart:69]:
```suggestion
                index > 0 ? widget.transactions[index - 1].txnTime : null,
```

**Review by gabaldon — CHANGES_REQUESTED** [review]

**Review by gabaldon — APPROVED** [review]
